// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proj.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proj_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proj_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proj_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proj_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proj_2eproto;
class Loading_Msg;
class Loading_MsgDefaultTypeInternal;
extern Loading_MsgDefaultTypeInternal _Loading_Msg_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Loading_Msg* Arena::CreateMaybeMessage<::Loading_Msg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Loading_Msg :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Loading_Msg) */ {
 public:
  Loading_Msg();
  virtual ~Loading_Msg();

  Loading_Msg(const Loading_Msg& from);
  Loading_Msg(Loading_Msg&& from) noexcept
    : Loading_Msg() {
    *this = ::std::move(from);
  }

  inline Loading_Msg& operator=(const Loading_Msg& from) {
    CopyFrom(from);
    return *this;
  }
  inline Loading_Msg& operator=(Loading_Msg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Loading_Msg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Loading_Msg* internal_default_instance() {
    return reinterpret_cast<const Loading_Msg*>(
               &_Loading_Msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Loading_Msg& a, Loading_Msg& b) {
    a.Swap(&b);
  }
  inline void Swap(Loading_Msg* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Loading_Msg* New() const final {
    return CreateMaybeMessage<Loading_Msg>(nullptr);
  }

  Loading_Msg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Loading_Msg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Loading_Msg& from);
  void MergeFrom(const Loading_Msg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Loading_Msg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Loading_Msg";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proj_2eproto);
    return ::descriptor_table_proj_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCpuLoadFieldNumber = 1,
    kBpuLoadFieldNumber = 2,
    kMemLoadFieldNumber = 3,
    kGpuLoadFieldNumber = 4,
  };
  // float cpu_load = 1;
  void clear_cpu_load();
  float cpu_load() const;
  void set_cpu_load(float value);

  // float bpu_load = 2;
  void clear_bpu_load();
  float bpu_load() const;
  void set_bpu_load(float value);

  // float mem_load = 3;
  void clear_mem_load();
  float mem_load() const;
  void set_mem_load(float value);

  // float gpu_load = 4;
  void clear_gpu_load();
  float gpu_load() const;
  void set_gpu_load(float value);

  // @@protoc_insertion_point(class_scope:Loading_Msg)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  float cpu_load_;
  float bpu_load_;
  float mem_load_;
  float gpu_load_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proj_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Loading_Msg

// float cpu_load = 1;
inline void Loading_Msg::clear_cpu_load() {
  cpu_load_ = 0;
}
inline float Loading_Msg::cpu_load() const {
  // @@protoc_insertion_point(field_get:Loading_Msg.cpu_load)
  return cpu_load_;
}
inline void Loading_Msg::set_cpu_load(float value) {
  
  cpu_load_ = value;
  // @@protoc_insertion_point(field_set:Loading_Msg.cpu_load)
}

// float bpu_load = 2;
inline void Loading_Msg::clear_bpu_load() {
  bpu_load_ = 0;
}
inline float Loading_Msg::bpu_load() const {
  // @@protoc_insertion_point(field_get:Loading_Msg.bpu_load)
  return bpu_load_;
}
inline void Loading_Msg::set_bpu_load(float value) {
  
  bpu_load_ = value;
  // @@protoc_insertion_point(field_set:Loading_Msg.bpu_load)
}

// float mem_load = 3;
inline void Loading_Msg::clear_mem_load() {
  mem_load_ = 0;
}
inline float Loading_Msg::mem_load() const {
  // @@protoc_insertion_point(field_get:Loading_Msg.mem_load)
  return mem_load_;
}
inline void Loading_Msg::set_mem_load(float value) {
  
  mem_load_ = value;
  // @@protoc_insertion_point(field_set:Loading_Msg.mem_load)
}

// float gpu_load = 4;
inline void Loading_Msg::clear_gpu_load() {
  gpu_load_ = 0;
}
inline float Loading_Msg::gpu_load() const {
  // @@protoc_insertion_point(field_get:Loading_Msg.gpu_load)
  return gpu_load_;
}
inline void Loading_Msg::set_gpu_load(float value) {
  
  gpu_load_ = value;
  // @@protoc_insertion_point(field_set:Loading_Msg.gpu_load)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proj_2eproto
